# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#Apaga os medicos cadastrados para não ficar sem refencia
Medico.delete_all
# Inicio da criação das Especialidades no Banco de Dados
Especialidade.delete_all
Especialidade.create(:id => 1, :descricao => "Acupuntura")
Especialidade.create(:id => 2, :descricao => "Alergia e Imunologia")
Especialidade.create(:id => 3, :descricao => "Anestesiologia")
Especialidade.create(:id => 4, :descricao => "Angiologia")
Especialidade.create(:id => 5, :descricao => "Cancerologia (oncologia)")
Especialidade.create(:id => 6, :descricao => "Cardiologia")
Especialidade.create(:id => 7, :descricao => "Cirurgia Cardiovascular")
Especialidade.create(:id => 8, :descricao => "Cirurgia da Mão")
Especialidade.create(:id => 9, :descricao => "Cirurgia de Cabeça e Pescoço")
Especialidade.create(:id => 10, :descricao => "Cirurgia do Aparelho Digestório")
Especialidade.create(:id => 11, :descricao => "Cirurgia Geral")
Especialidade.create(:id => 12, :descricao => "Cirurgia Pediátrica")
Especialidade.create(:id => 13, :descricao => "Cirurgia Plástica")
Especialidade.create(:id => 14, :descricao => "Cirurgia Torácica")
Especialidade.create(:id => 15, :descricao => "Cirurgia Vascular")
Especialidade.create(:id => 16, :descricao => "Clínica Médica")
Especialidade.create(:id => 17, :descricao => "Coloproctologia")
Especialidade.create(:id => 18, :descricao => "Dermatologia")
Especialidade.create(:id => 19, :descricao => "Endocrinologia e Metabologia")
Especialidade.create(:id => 20, :descricao => "Endoscopia")
Especialidade.create(:id => 21, :descricao => "Gastroenterologia")
Especialidade.create(:id => 22, :descricao => "Genética médica")
Especialidade.create(:id => 23, :descricao => "Geriatria")
Especialidade.create(:id => 24, :descricao => "Ginecologia e Obstetrícia")
Especialidade.create(:id => 25, :descricao => "Hematologia e Hemoterapia")
Especialidade.create(:id => 26, :descricao => "Homeopatia")
Especialidade.create(:id => 27, :descricao => "Infectologia")
Especialidade.create(:id => 28, :descricao => "Mastologia")
Especialidade.create(:id => 29, :descricao => "Medicina de Família e Comunidade")
Especialidade.create(:id => 30, :descricao => "Medicina do Trabalho")
Especialidade.create(:id => 31, :descricao => "Medicina do Tráfego")
Especialidade.create(:id => 32, :descricao => "Medicina Esportiva")
Especialidade.create(:id => 33, :descricao => "Medicina Física e Reabilitação")
Especialidade.create(:id => 34, :descricao => "Medicina Intensiva")
Especialidade.create(:id => 35, :descricao => "Medicina Legal")
Especialidade.create(:id => 36, :descricao => "Medicina Nuclear")
Especialidade.create(:id => 37, :descricao => "Medicina Preventiva e Social")
Especialidade.create(:id => 38, :descricao => "Nefrologia")
Especialidade.create(:id => 39, :descricao => "Neurocirurgia")
Especialidade.create(:id => 40, :descricao => "Neurologia")
Especialidade.create(:id => 41, :descricao => "Nutrologia")
Especialidade.create(:id => 42, :descricao => "Oftalmologia")
Especialidade.create(:id => 43, :descricao => "Ortopedia e Traumatologia")
Especialidade.create(:id => 44, :descricao => "Otorrinolaringologia")
Especialidade.create(:id => 45, :descricao => "Patologia")
Especialidade.create(:id => 46, :descricao => "Pediatria")
Especialidade.create(:id => 47, :descricao => "Neonatologia")
Especialidade.create(:id => 48, :descricao => "Pneumologia")
Especialidade.create(:id => 49, :descricao => "Psiquiatria")
Especialidade.create(:id => 50, :descricao => "Radiologia e Diagnóstico por Imagem")
Especialidade.create(:id => 51, :descricao => "Radioterapia")
Especialidade.create(:id => 52, :descricao => "Reumatologia")
Especialidade.create(:id => 53, :descricao => "Urologia")
#Fim da criação das Especialidades Médicas

#Inicio da Inserção dos Estados brasileiros
Estado.delete_all
Estado.create(:nome => "Acre", :uf => "AC")
Estado.create(:nome => "Alagoas", :uf => "AL")
Estado.create(:nome => "Amapá", :uf => "AP")
Estado.create(:nome => "Amazonas", :uf => "AM")
Estado.create(:nome => "Bahia", :uf => "BA")
Estado.create(:nome => "Ceará", :uf => "CE")
Estado.create(:nome => "Distrito Federal", :uf => "DF")
Estado.create(:nome => "Espírito Santo", :uf => "ES")
Estado.create(:nome => "Goiás", :uf => "GO")
Estado.create(:nome => "Maranhão", :uf => "MA")
Estado.create(:nome => "Mato Grosso", :uf => "MT")
Estado.create(:nome => "Mato Grosso do Sul", :uf => "MS")
Estado.create(:nome => "Minas Gerais", :uf => "MG")
Estado.create(:nome => "Pará", :uf => "PA")
Estado.create(:nome => "Paraíba", :uf => "PB")
Estado.create(:nome => "Paraná", :uf => "PR")
Estado.create(:nome => "Pernambuco", :uf => "PE")
Estado.create(:nome => "Piauí", :uf => "PI")
Estado.create(:nome => "Rio de Janeiro", :uf => "RJ")
Estado.create(:nome => "Rio Grande do Norte", :uf => "RN")
Estado.create(:nome => "Rio Grande do Sul", :uf => "RS")
Estado.create(:nome => "Rondônia", :uf => "RO")
Estado.create(:nome => "Roraima", :uf => "RR")
Estado.create(:nome => "Santa Catarina", :uf => "SC")
Estado.create(:nome => "São Paulo", :uf => "SP")
Estado.create(:nome => "Sergipe", :uf => "SE")
Estado.create(:nome => "Tocantins", :uf => "TO")
#Fim da criação dos Estados