# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Inicio da criação das Especialidades no Banco de Dados
Especialidade.delete_all
Especialidade.create(:descricao => "Acupuntura")
Especialidade.create(:descricao => "Alergia e Imunologia")
Especialidade.create(:descricao => "Anestesiologia")
Especialidade.create(:descricao => "Angiologia")
Especialidade.create(:descricao => "Cancerologia (oncologia)")
Especialidade.create(:descricao => "Cardiologia")
Especialidade.create(:descricao => "Cirurgia Cardiovascular")
Especialidade.create(:descricao => "Cirurgia da Mão")
Especialidade.create(:descricao => "Cirurgia de Cabeça e Pescoço")
Especialidade.create(:descricao => "Cirurgia do Aparelho Digestório")
Especialidade.create(:descricao => "Cirurgia Geral")
Especialidade.create(:descricao => "Cirurgia Pediátrica")
Especialidade.create(:descricao => "Cirurgia Plástica")
Especialidade.create(:descricao => "Cirurgia Torácica")
Especialidade.create(:descricao => "Cirurgia Vascular")
Especialidade.create(:descricao => "Clínica Médica")
Especialidade.create(:descricao => "Coloproctologia")
Especialidade.create(:descricao => "Dermatologia")
Especialidade.create(:descricao => "Endocrinologia e Metabologia")
Especialidade.create(:descricao => "Endoscopia")
Especialidade.create(:descricao => "Gastroenterologia")
Especialidade.create(:descricao => "Genética médica")
Especialidade.create(:descricao => "Geriatria")
Especialidade.create(:descricao => "Ginecologia e Obstetrícia")
Especialidade.create(:descricao => "Hematologia e Hemoterapia")
Especialidade.create(:descricao => "Homeopatia")
Especialidade.create(:descricao => "Infectologia")
Especialidade.create(:descricao => "Mastologia")
Especialidade.create(:descricao => "Medicina de Família e Comunidade")
Especialidade.create(:descricao => "Medicina do Trabalho")
Especialidade.create(:descricao => "Medicina do Tráfego")
Especialidade.create(:descricao => "Medicina Esportiva")
Especialidade.create(:descricao => "Medicina Física e Reabilitação")
Especialidade.create(:descricao => "Medicina Intensiva")
Especialidade.create(:descricao => "Medicina Legal")
Especialidade.create(:descricao => "Medicina Nuclear")
Especialidade.create(:descricao => "Medicina Preventiva e Social")
Especialidade.create(:descricao => "Nefrologia")
Especialidade.create(:descricao => "Neurocirurgia")
Especialidade.create(:descricao => "Neurologia")
Especialidade.create(:descricao => "Nutrologia")
Especialidade.create(:descricao => "Oftalmologia")
Especialidade.create(:descricao => "Ortopedia e Traumatologia")
Especialidade.create(:descricao => "Otorrinolaringologia")
Especialidade.create(:descricao => "Patologia")
Especialidade.create(:descricao => "Pediatria")
Especialidade.create(:descricao => "Neonatologia")
Especialidade.create(:descricao => "Pneumologia")
Especialidade.create(:descricao => "Psiquiatria")
Especialidade.create(:descricao => "Radiologia e Diagnóstico por Imagem")
Especialidade.create(:descricao => "Radioterapia")
Especialidade.create(:descricao => "Reumatologia")
Especialidade.create(:descricao => "Urologia")
#Fim da criação das Especialidades Médicas